models:
  - "msmarco-MiniLM-L6-cos-v5"
  - "msmarco-distilbert-dot-v5"
  - "multi-qa-MiniLM-L6-cos-v1"
  - "multi-qa-distilbert-cos-v1"
  # - "multi-qa-mpnet-base-cos-v1"
  - "all-MiniLM-L6-v2"
  - "all-distilroberta-v1"
  - "all-mpnet-base-v2"
  # - "BAAI/bge-base-en"
  # - "BAAI/bge-large-en"
  - "BAAI/bge-base-en-v1.5"
  - "BAAI/llm-embedder"
  # - "intfloat/e5-mistral-7b-instruct"
  - "intfloat/multilingual-e5-large"
  - "intfloat/multilingual-e5-small"
  - "intfloat/e5-large-v2"
  - "intfloat/e5-small-v2"
  - "llmrails/ember-v1"
  - "cross-encoder/ms-marco-MiniLM-L-6-v2"
  - "cross-encoder/ms-marco-TinyBERT-L-2-v2"
  - "cross-encoder/qnli-distilroberta-base"
  - "cross-encoder/stsb-TinyBERT-L-4"
  - "cross-encoder/stsb-distilroberta-base"
  - "cross-encoder/quora-distilroberta-base"
  # - "cross-encoder/nli-deberta-v3-xsmall"
  # - "cross-encoder/nli-MiniLM2-L6-H768"
  - "BAAI/bge-reranker-base"
  - "BAAI/bge-reranker-large"


datasets:
  # english
  - 'mteb/scidocs-reranking'
  - 'mteb/stackoverflowdupquestions-reranking'
  - "mteb/askubuntudupquestions-reranking"
  # french
  # - "OrdalieTech/Ordalie-FR-Reranking-benchmark"
  - "lyon-nlp/mteb-fr-reranking-alloprof-s2p"
  # - "lyon-nlp/mteb-fr-reranking-syntec-s2p"
  # - "OrdalieTech/MIRACL-FR-Reranking-benchmark"
  # - "sproos/mindsmall-fr"
  # chinese
  - "C-MTEB/CMedQAv1-reranking"
  - "C-MTEB/Mmarco-reranking"
