models:
  - "intfloat/e5-mistral-7b-instruct"
#  - "intfloat/multilingual-e5-large"
  - "intfloat/multilingual-e5-small"
  # - "intfloat/e5-large-v2"
  - "intfloat/e5-small-v2"
#  - "llmrails/ember-v1"
#  - "cross-encoder/ms-marco-MiniLM-L-6-v2"
#  - "cross-encoder/ms-marco-TinyBERT-L-2-v2"
#  - "cross-encoder/qnli-distilroberta-base"
#  - "cross-encoder/stsb-TinyBERT-L-4"
#  - "cross-encoder/stsb-distilroberta-base"
#  - "cross-encoder/quora-distilroberta-base"
#  - "cross-encoder/nli-deberta-v3-xsmall"
#  - "cross-encoder/nli-MiniLM2-L6-H768"
#  - "BAAI/bge-reranker-base"
#  - "BAAI/bge-reranker-large"


datasets:
  # english
  - "C-MTEB/Mmarco-reranking" # quick

